### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by benwilson512** [nerves-project/nerves-project.github.com#12]
Hey!

Not sure if github changed the pages format on your or something, but there's a lot of links to `.html` pages that are dead until you go to the url and replace the `.html` with `/` e.g. http://nerves-project.org/learn/prepare.html => http://nerves-project.org/learn/prepare/

This causes a fair bit of confusion on the learning page because basically all the content appears dead at first glance.

I'd open a PR but I'm not super familiar with github pages stuff and I don't want to miss anything, sorry!

**Comment by fhunleth** [comment]
Ugh - I thought I fixed things with the GitHub pages upgrade a couple months ago. Thanks for reporting this. I hope that they haven't been broke for long.

**Comment by GregMefford** [comment]
All fixed.
Thanks again, @benwilson512 for taking the time to report it! :star2: :+1:
