### ISSUE TITLE
Document mix (vs bakeware) build process, new talk

### ISSUE THREAD

**Issue by bruce** [nerves-project/nerves-project.github.com#19]
@mobileoverlord's talk at ElixirConf EU was especially interesting to people (like me) that were interested in Nerves but had wanted a build toolchain closer to other Elixir projects (eg, using `mix`). To help with project momentum & uptake I think it probably makes sense to update the website content in a few places I noticed trying to get started:

- [x] An addition to http://nerves-project.org/news/ mentioning the new approach / Justin's talk
- [x] A links/embedding to the talk from ElixirConf EU: [video](https://youtu.be/118-g0ODfgg) | [slides](http://s3.amazonaws.com/erlang-conferences-production/media/files/000/000/089/original/NervesRevolution.pdf?1463065757) at http://nerves-project.org/watch/
- [x] Updates to http://nerves-project.org/learn/ describing the new build ecosystem

**Comment by GregMefford** [comment]
Thanks for your contribution! :sparkles: :balloon: 

I added Justin's talk to the /watch page in 93a2074.

The /learn stuff is kind of in flux right now because the main body of docs is over at [HexDocs](https://hexdocs.pm/nerves/getting-started.html) now. We need to figure out how we want to cross-link to there in a way that makes sense. I'm open to suggestions if you have any thoughts about that!

**Comment by GregMefford** [comment]
Added a news item about recent changes in 1a65cf7.

I'll work shortly on cleaning up the /learn page. I was hoping to do it over the weekend, but ended up being too busy.

**Comment by bruce** [comment]
Thanks @GregMefford -- this sounds like great progress!

**Comment by GregMefford** [comment]
I replaced the **learn** link with a **get started** link, that goes to the updated [HexDocs Getting Started](https://hexdocs.pm/nerves/getting-started.html) page. Most of the content that used to be on the website is already covered there, and I'll continue to refine what's there.

Hopefully that will help eliminate the confusion between the old Bakeware method and the new Mix method of building firmware.
