### ISSUE TITLE
Update README install instructions

### ISSUE THREAD

**Issue by bendiken** [nerves-project/nerves-project.github.com#25]
The set-up instructions in the README instructing the use of Ruby 2.0 are unworkable at the moment, since some transitive dependency is pulling in ActiveSupport 5.0 which actually requires Ruby 2.2+:

    $ bundle install
    Fetching gem metadata from https://rubygems.org/
    Fetching version metadata from https://rubygems.org/
    Fetching dependency metadata from https://rubygems.org/
    Resolving dependencies...
    Rubygems 2.0.14 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
    Installing concurrent-ruby 1.0.2
    Installing i18n 0.7.0
    Installing minitest 5.9.0
    Installing thread_safe 0.3.5
    Installing addressable 2.4.0
    Installing coffee-script-source 1.10.0
    Installing execjs 2.7.0
    Installing colorator 0.1
    Installing ffi 1.9.14 with native extensions
    Installing multipart-post 2.0.0
    Installing gemoji 2.1.0
    Installing net-dns 0.8.0
    Installing public_suffix 1.5.3
    Installing sass 3.4.22
    Installing rb-fsevent 0.9.7
    Installing kramdown 1.11.1
    Installing liquid 3.0.6
    Installing mercenary 0.3.6
    Installing rouge 1.11.1
    Installing safe_yaml 1.0.4
    Installing jekyll-feed 0.5.1
    Installing mini_portile2 2.1.0
    Installing pkg-config 1.1.7
    Installing jekyll-paginate 1.1.0
    Installing jekyll-sitemap 0.10.0
    Installing terminal-table 1.6.0
    Using bundler 1.12.5
    Installing tzinfo 1.2.2
    Installing coffee-script 2.4.1
    Installing ethon 0.9.0
    Installing rb-inotify 0.9.7
    Installing faraday 0.9.2
    Installing jekyll-sass-converter 1.3.0
    Installing nokogiri 1.6.8 with native extensions
    Installing activesupport 5.0.0

    Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
    Installing jekyll-coffeescript 1.0.1
    Installing typhoeus 0.8.0
    Installing listen 3.0.6
    Installing sawyer 0.7.0
    An error occurred while installing activesupport (5.0.0), and Bundler cannot continue.
    Make sure that `gem install activesupport -v '5.0.0'` succeeds before bundling.

    $ ruby2.0 --version
    ruby 2.0.0p384 (2014-01-12) [x86_64-linux-gnu]
    $ gem2.0 --version
    2.0.14
    $ bundler --version
    Bundler version 1.12.5

The above was on Ubuntu 14.04.4 LTS with the system `ruby2.0` and `ruby2.0-dev` packages installed, and after `sudo gem2.0 install bundler`. (No RVM, as it is orthogonal to the issue.)

The dependency hell is no doubt properly an upstream GitHub Pages and/or Jekyll issue, but nonetheless the README's instructions here need updating somehow or another so as to enable potential contributors to get set up with the repository locally.

**Comment by bendiken** [comment]
https://github.com/github/pages-gem/issues/181 looks relevant.

**Comment by bendiken** [comment]
The workaround is to explicitly lock ActiveSupport to the last Ruby 2.0-compatible release:

    diff --git a/Gemfile b/Gemfile
    index 97355ea..649f275 100644
    --- a/Gemfile
    +++ b/Gemfile
    @@ -1,3 +1,4 @@
     source 'https://rubygems.org'
 
    +gem 'activesupport', '4.2.6'
     gem 'github-pages'

I could submit a pull request for this addition. However, perhaps a preferable solution might be to just recommend the use of Ruby 2.2+? (Assuming that doesn't introduce other problems.)

**Comment by mitjajez** [comment]
`gem 'activesupport', '4.2.6'` in Gemfile does solve my problem.

**Comment by fhunleth** [comment]
@bendiken and @mitjajez: I don't do any Ruby programming, so I don't have strong feelings on this. I do know that whatever instructions we have here regularly break, and I don't understand they're so brittle. What do you think is the best route forward? Locking activesupport? updating to Ruby 2.2?

**Comment by mitjajez** [comment]
I don't do any Ruby programming too, but i belive that it's easier for users to lock activesupport v4.2, since i find very hard to install Ruby >= 2.2 on Debian. (I know, this distro uses oldest stuff comparing to others)
Activesupport 5.0 just came up, and as dependency it brokes few readme files for other projects too.

**Comment by bendiken** [comment]
@fhunleth The GH Pages / Jekyll stack is a bit brittle, indeed. Another problematic transitive dependency is Nokogiri, which requires native extension compilation and can be a real bother on e.g. OS X.

I'll go ahead and submit a pull request for locking the ActiveSupport for now, since that is the simplest change that fixes the pressing problem.

**Comment by fhunleth** [comment]
@bendiken and @mitjajez - thank you both so much for debugging this and @bendiken for the PR.

**Comment by bendiken** [comment]
@fhunleth Thanks for merging. And happy to help on any other Ruby issues, it's pretty familiar ground.

**Comment by GregMefford** [comment]
@bendiken and @mitjajez Thanks again for taking the time to figure this out, and for caring enough in the first place about having helpful docs on this.

I laugh as it wasn't long ago that I was saying we should keep the website using Jekyll since it's so simple for people to contribute changes to. I have some experience with Ruby, and I think the bottom line is that Rubyists are frequently having to update to keep up with the new versions of things. It's possible to lock versions of things, but inevitably it becomes easier to get things updated to work better for people getting started with a new version of Ruby, for example.

This fix seems fine to me.
